<Project>

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <Deterministic>true</Deterministic>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <PathMap>$(RepoRoot)=.</PathMap>
  </PropertyGroup>

</Project>
