// (c) DeNA Co., Ltd.

using System.Collections.Immutable;

namespace Waffle.ModelProxy;

/// <summary>
/// Holds naming information for a type and its corresponding proxy wrapper counterpart
/// generated by the <c>ModelProxy</c> source generator.
/// </summary>
internal readonly struct ModelProxyTypeInfo
{
    /// <summary>The unqualified (short) name of the original type.</summary>
    public readonly string OriginalShortName;

    /// <summary>The parent-prefixed name of the original type, excluding the namespace.</summary>
    public readonly string OriginalLongName;

    /// <summary>The fully qualified name of the original type.</summary>
    public readonly string OriginalFullName;

    /// <summary>The containing type names (parent chain) of the original type, ordered outermost first.</summary>
    public readonly string[] OriginalParents;

    /// <summary>A dot-separated prefix built from <see cref="OriginalParents"/>, with a trailing dot, or empty when there are no parent types.</summary>
    public readonly string OriginalParentPrefix;

    /// <summary>The unqualified (short) name of the generated proxy wrapper type.</summary>
    public readonly string ProxyShortName;

    /// <summary>The parent-prefixed name of the generated proxy wrapper type, excluding the namespace.</summary>
    public readonly string ProxyLongName;

    /// <summary>The fully qualified name of the generated proxy wrapper type.</summary>
    public readonly string ProxyFullName;

    /// <summary>The containing type names (parent chain) for the generated proxy wrapper type, ordered outermost first.</summary>
    public readonly string[] ProxyParents;

    /// <summary>A dot-separated prefix built from <see cref="ProxyParents"/>, with a trailing dot, or empty when there are no parent types.</summary>
    public readonly string ProxyParentPrefix;

    /// <summary>The fully qualified namespace string, including the <c>global::</c> alias prefix.</summary>
    public readonly string FullNs;

    /// <summary>The namespace string without the <c>global::</c> alias prefix.</summary>
    public readonly string Ns;

    /// <summary>The member information</summary>
    public readonly ImmutableArray<MemberInfo> Members;

    /// <summary>Tuples to generate proxy definitions</summary>
    public readonly ImmutableArray<TupleInfo> Tuples;

    /// <summary>The unqualified (short) name of the generated proxy-list wrapper type.</summary>
    public string ProxyListShortName => $"{ProxyShortName}List";

    /// <summary>The parent-prefixed name of the generated proxy-list wrapper type, excluding the namespace.</summary>
    public string ProxyListLongName => $"{ProxyLongName}List";

    /// <summary>
    /// Initializes a new <see cref="ModelProxyTypeInfo"/> by deriving all name components from the given type symbol.
    /// </summary>
    internal ModelProxyTypeInfo(ModelProxyTypeInfoForCache cache) : this()
    {
        OriginalShortName = cache.OriginalShortName;
        OriginalFullName = cache.OriginalFullName;
        FullNs = cache.FullNameSpace;
        Members = cache.Members;
        Tuples = cache.Tuples;

        Ns = FullNs.RemovePrefix("global::");
        OriginalParents = OriginalFullName
            .RemovePrefix(FullNs).RemoveSuffix(OriginalShortName)
            .Split('.').Where(it => !string.IsNullOrEmpty(it)).ToArray();
        OriginalParentPrefix = OriginalParents.Length > 0 ? string.Join(".", OriginalParents) + "." : "";
        OriginalLongName = $"{OriginalParentPrefix}{OriginalShortName}";

        ProxyShortName = $"{OriginalShortName}Proxy";
        ProxyParents = OriginalParents.Select(it => $"{it}Proxy").ToArray();
        ProxyParentPrefix = ProxyParents.Length > 0 ? string.Join(".", ProxyParents) + "." : "";
        ProxyLongName = $"{ProxyParentPrefix}{ProxyShortName}";
        ProxyFullName = $"{FullNs}.{ProxyLongName}";
    }
}
