// (c) DeNA Co., Ltd.

namespace Waffle.ModelProxy;

internal static class IsgHelper
{
    /// <summary>
    /// Generates the file content that defines a single attribute
    /// </summary>
    /// <param name="parentNamespace">Parent namespace for the attribute</param>
    /// <param name="usingNamespaces">Additional namespaces to add as using directives</param>
    /// <param name="target">Attribute target. Multiple targets can be combined with |</param>
    /// <param name="attrName">Attribute name (the "Attribute" suffix is not required)</param>
    /// <param name="attrContent">Body of the attribute class. Indentation is not required</param>
    /// <param name="comment">XML doc comment to embed in the generated attribute</param>
    internal static string AttributeDefinitionFile(
        string parentNamespace,
        string[] usingNamespaces,
        AttributeTargets target,
        string attrName,
        string attrContent = "",
        string comment = "")
    {
        var targets = new List<AttributeTargets>();

        foreach (var e in Enum.GetValues<AttributeTargets>())
        {
            if (e is AttributeTargets.All)
            {
                continue;
            }

            if ((target & e) == e)
            {
                targets.Add(e);
            }
        }

        //lang=cs
        return $$"""
            {{Header()}}

            using System;
            {{string.Join("\n", usingNamespaces.Where(it => it is not "System").Select(it => $"using {it};"))}}

            {{WrapInNamespace(parentNamespace, /*lang=cs*/ $$"""
                /// <summary>
                {{string.Join("\n", comment.Split('\n').Select(it => $"/// {it}").ToArray())}}
                /// </summary>
                [AttributeUsage({{string.Join(" | ", targets.Select(it => $"AttributeTargets.{it}").ToArray())}})]
                public class {{attrName}}Attribute : Attribute 
                { 
                {{InsertIndent(attrContent, 1)}}
                }
                """)}}
            """;
    }

    /// <summary>
    /// Prepends indentation to each line (4 spaces per <paramref name="indentLevel"/> level).
    /// </summary>
    internal static string InsertIndent(string source, int indentLevel)
    {
        if (indentLevel <= 0 || source.Length == 0)
        {
            return source;
        }

        var indent = new string(' ', indentLevel * 4);
        var breakIndent = "\n" + indent;
        var hasLastBreak = source[^1] == '\n';
        if (hasLastBreak)
        {
            source = source[..^1];
        }

        source = indent + source.Replace("\n", breakIndent);
        if (hasLastBreak)
        {
            source += '\n';
        }

        return source;
    }

    /// <summary>
    /// Returns the auto-generated tag, copyright notice, and #nullable enable directive.
    /// Intended to be placed at the top of a generated file.
    /// </summary>
    internal static string Header()
    {
        //lang=cs
        return """
            // <auto-generated>
            //     Generated by Waffle.ModelProxy. DO NOT EDIT!
            // </auto-generated>

            // (c) DeNA Co., Ltd.

            #nullable enable
            """;
    }

    /// <summary>
    /// Wraps the given content in a namespace declaration with the specified parent namespace.
    /// </summary>
    internal static string WrapInNamespace(string parentNamespace, string content)
    {
        //lang=cs
        return $$"""
            namespace {{parentNamespace}}
            {
            {{InsertIndent(content, 1)}}
            }
            """;
    }
}
